#alertmanager-config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: monitor
data:

  #alertmanager配置#
  config.yml: |-
    # 全局配置项
    global:
      resolve_timeout: 5m
    # 路由
    route:
      group_by: ['alertname'] # 报警分组依据
      group_wait: 20s #组等待时间
      group_interval: 20s # 发送前等待时间
      repeat_interval: 12h #重复周期
      receiver: 'dingtalk'
    # 警报接收者
    receivers:
    - name: 'dingtalk'
      webhook_configs:
      - send_resolved: true
        url: http://localhost:8060/dingtalk/web1/send
