
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: {{ monitor_namespace }}
  labels:
    app: loki
data:
  loki.yaml: |

    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      path_prefix: /data/loki
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /data/loki/chunks
          rules_directory: /data/loki/rules

    schema_config:
      configs:
      - from: 2024-05-15
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

    storage_config:
      filesystem:
        directory: /data/loki/chunks

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h # 7天


    #alert
    ruler:
      alertmanager_url: http://alertmanager:9093
      enable_alertmanager_v2: true
      enable_api: true               	#启用loki rules
      enable_sharding: true           #支持ruler多实例
      ring:                  		      #用于支持多实例和分片
        kvstore:
          store: inmemory
      rule_path: /data/loki/tmp_rules #rules规则临时路径
      storage:                        # rules规则存储
        type: local
        local:
          directory: /etc/loki-rules #rules规则文件路径

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rule
  namespace: {{ monitor_namespace }}
data:
  rule.ingress.yaml: |
    groups:
    - name: k8s
      rules:
{%raw%}
      - alert: ingressStatus5xx
        expr: sum by (proxy_name, host) (count_over_time({job=~".*ingress-nginx", status=~"5.*"} [3m])) > 10
        for: 30s
        labels:
          severity: warning
          instance: "{{$labels.proxy_name}}"
        annotations:
          summary: "Found 5xx error from ingress"
          description: "error-count: {{ $value }} from {{$labels.host}}"
          title: "ingress-error-log"
{%endraw%}
