
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: {{ monitor_namespace }}
  labels:
    app: loki
data:
  loki.yaml: |

    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      path_prefix: /data/loki
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /data/loki/chunks
          rules_directory: /data/loki/rules

    schema_config:
      configs:
      - from: 2024-05-15
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

    storage_config:
      filesystem:
        directory: /data/loki/chunks

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h # 7天

