apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail
  namespace: {{ monitor_namespace }}
  labels:
    app: promtail
data:
  promtail.yaml: |

    client:
      backoff_config:
        max_period: 5m 
        max_retries: 10
        min_period: 500ms
      batchsize: 1048576
      batchwait: 1s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 10s
    scrape_configs:

    - job_name: kubernetes-pods-app
      pipeline_stages:
        - cri: {}
        - labelallow:
            - app
            - pod
            - job
            - container
            - namespace
            - loki_job
        - drop:
            expression: ".*kube-probe.*|.*kube-probe.*|.*controller.go.*|.*Skipping metric.*"
        - static_labels:
            loki_job: 'kubernetes-pods-app'
        - multiline:
            #firstline: '^\w'
            firstline: '^[a-zA-Z0-9].*'
            max_lines: 128
            max_wait_time: 3s
        - replace:
            expression: "password(\\S+)"
            replace: "password***"
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      #namespaces排除
      - action: drop
        source_labels: [__meta_kubernetes_namespace]
        regex: 'monitor|velero|custom-metrics|ingress-nginx|kube-node-lease'
      # 排除ingress
      - action: drop
        source_labels:
        - __meta_kubernetes_pod_name
        regex: '^ingress-ngin.*|^nginx-ingres.*'
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__


    - job_name: ingress-nginx
      pipeline_stages:
        - cri: {}
        - static_labels:
            loki_job: 'ingress-nginx'
        - labeldrop:
            - 'pod_template_generation'
            - 'controller_revision_hash'
            - 'app_kubernetes_io_instance'
            - 'app_kubernetes_io_component'
            - 'filename'
            - 'detected_level'
            - 'pod_template_hash'
            - 'app_kubernetes_io_version'
            - 'app_kubernetes_io_part_of'
            - 'app_kubernetes_io_name'
        - drop:
            expression: ".*healthcheck.*|.*kube-probe.*|.*controller.go.*|.*00] TCP .*"
        - json:
            expressions:
              host: host
              status: status
              ip: remote_addr
              request_uri: request_uri
              proxy_name: proxy_upstream_name
        - labels:
            host:
            status:
            ip:
            request_uri:
            proxy_name:
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      #ingress筛选
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_name
        regex: '^ingress-ngin.*|^nginx-ingres.*'
      - source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
{% if env == 'prod-aliyun' %}
        - __meta_kubernetes_pod_label_app
{% else %}
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
{% endif %}
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__

