---

apiVersion: v1
kind: Service
metadata:
  name: {{ k8s_pod_name }}
  namespace: {{ namespace }}
spec:
  selector:
    app: {{ k8s_pod_name }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
