---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ k8s_pod_name }}-config
  namespace: {{ namespace }}
data:
  nginx.conf: |-

    #ngix主配置
    user   nginx;
    worker_processes   auto;
    worker_rlimit_nofile   4096;
    pid        /var/run/nginx.pid;
    events {
    worker_connections  4096;
    multi_accept   on;
    use   epoll;
    }


    http {
    sendfile   on;
    tcp_nopush on;
    tcp_nodelay on;
    types_hash_max_size 2048;
    #隐藏版本显示
    server_tokens   off;
    charset UTF-8;
    #上传文件大小
    client_max_body_size 20m;
    #缓存
    client_header_buffer_size 4k;
    open_file_cache max=10240 inactive=20s; 
    open_file_cache_valid 60s; 
    open_file_cache_min_uses 1; 
    open_file_cache_errors on;
    #超时
    keepalive_timeout 50; 
    client_header_timeout 20; 
    client_body_timeout 20; 
    reset_timedout_connection on; 
    send_timeout 20; 
    #IP连接数
    # limit_conn_zone $binary_remote_addr zone=one:10m;
    # limit_conn addr 100;
    #FastCGI
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k; 
    #index
    include /etc/nginx/mime.types;
    index index.html;
    proxy_cache_path /data/cache levels=1:2 keys_zone=nginx_cache:100m inactive=1d max_size=512m;

    #head
    {% if docker_build_nginx_headers is defined %}
    {% for header in docker_build_nginx_headers %}
    add_header {{ header.name }} "{{ header.value }}";
    {% endfor %}
    {% endif %}

    #real_ip
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
    set_real_ip_from  0.0.0.0/0;

    #日志格式
    log_format main  '$remote_addr [$time_local] '
        ' $status "$request" $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';

    #日志
    access_log off;
    # access_log /var/log/nginx/access.log   main;
    error_log  /var/log/nginx/error.log error;

    # #gzip压缩
    # gzip   on;

    # nginx-module-vts, metrics for prometheus
    # vhost_traffic_status_zone;
    # vhost_traffic_status_filter_by_host on;
    # server {
    #     listen 9913;
    #     server_name nginx_vts_status
    #     access_log off;
    #     error_log /dev/null ;
    #     vhost_traffic_status off;
    #     # /metrics/format/html
    #     location /metrics {
    #         vhost_traffic_status_bypass_limit on;
    #         vhost_traffic_status_bypass_stats on;
    #         vhost_traffic_status_display;
    #         vhost_traffic_status_display_format prometheus;
    #     }
    # }

    server {
        listen 80 default_server;
        server_name _;
        root /data;

        access_log /var/log/nginx/access.log   main;
        error_page 404  http://$host;


        location /v1/ {
            alias /data/v1/;
        }

        location /v2/ {
            alias /data/v2/;
        }
        
        location /web/ {
            alias /data/v1/;
        }

        location / {
            alias /data/v1/;
            proxy_cache nginx_cache; 
            expires 6h;
        }

    }

    #
    }

