---

docker_image_name: app-v1
docker_image_tag: "{{ app_v1_version }}"

docker_build_service_type: jetty
docker_build_base_image: jetty9
docker_build_context:
  paths:
  # - /
  - /v1

k8s_pod_name: app-v1
k8s_pod_replicas: 2
k8s_pod_resources_requests_cpu: 100m
k8s_pod_resources_requests_memory: 512Mi
k8s_pod_resources_limits_cpu: 600m
k8s_pod_resources_limits_memory: 1Gi

# k8s_pod_readinessProbe_type: noCheck
# k8s_pod_readinessProbe_type: tcpSocket
k8s_pod_readinessProbe_type: httpGet
# k8s_pod_readinessProbe_endpoint: "/healthcheck"
k8s_pod_readinessProbe_endpoint: /v1/
# k8s_pod_readinessProbe_httpType: json
k8s_pod_readinessProbe_httpType: text
k8s_pod_readinessProbe_initialDelaySeconds: 12
k8s_pod_readinessProbe_periodSeconds: 10
k8s_pod_readinessProbe_failureThreshold: 3
k8s_pod_livenessProbe_initialDelaySeconds: 12

k8s_jvm_active_processor_count: 1
k8s_jvm_use_large_gc: false

k8s_configmap_enabled: true
k8s_service_enabled: true
k8s_ingress_enabled: false
k8s_log_pvc_add: true
k8s_data_pvc_add: false
k8s_data_pvc_dir: /data
k8s_pvc_replace_permissions: true
k8s_config_profiles_active_env: true
