{
 "title": "Java service Dashboard",
 "description": "By Elvin, https://gitee.com/alivv/ansible-app2k8s",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Core",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_join(label_replace(jvm_info{namespace=\"$namespace\",pod=\"$pod\"}, \"jdk\", \"$1\", \"runtime\", \"(.*) Runtime Environment\"), \"Ver\", \" \", \"jdk\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU Usage [2m]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=\"$pod\",image!=\"\",container!=\"POD\",container!=\"\"}[2m])) by (pod,namespace) / (sum(container_spec_cpu_quota{pod=\"$pod\",image!=\"\",container!=\"POD\",container!=\"\"}/100000) by (pod,namespace)) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage[2m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{pod=\"$pod\",namespace=\"$namespace\"}[2m]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{pod=\"$pod\",namespace=\"$namespace\"}[2m]))",
     "legendFormat": "User"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=\"$pod\",namespace=\"$namespace\",image!=\"\",container!=\"POD\",container!=\"\"}[2m]))/max(container_spec_cpu_quota{pod=\"$pod\",namespace=\"$namespace\",image!=\"\",container!=\"POD\",container!=\"\"})*100000",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"}/container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}*100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}/container_spec_memory_limit_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=\"$pod\"}/jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod=\"$pod\"}",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$pod\"}",
     "legendFormat": "Current"
    },
    {
     "expr": " jvm_threads_daemon{pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": " jvm_threads_peak{pod=\"$pod\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": " jvm_threads_deadlocked{pod=\"$pod\"}",
     "legendFormat": "Deadlocked"
    }
   ]
  },
  {
   "title": "JVM Class Loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod=\"$pod\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": " jvm_classes_loaded_total{pod=\"$pod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "JVM GC Time [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Count Increase [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{pod=\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Network [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=\"$pod\",namespace=\"$namespace\",container!=\"\"}[1m]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=\"$pod\",namespace=\"$namespace\",container!=\"\"}[1m]))*8",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "reserve",
   "type": "graph",
   "description": "Disk read writes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ]
  }
 ]
}