---
apiVersion: v1
kind: Secret
metadata:
  name: {{ docker_registry_key }}
  namespace: {{ namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ docker_registry_config_json }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ docker_registry_key }}
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ docker_registry_config_json }}


