---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: demo@elvin.vip
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx


{# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: zerossl-eab
stringData:
  secret: AuqZDUHtxlBsNoyBLden2iAWZOMBOh4msyTGPweXBnI5R7KgPDe25Xz6uZNLYCkpc0QvWJRah8tq2SWp02Vl9Qxxx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
  namespace: cert-manager
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: demo@elvin.vip
    externalAccountBinding:
      keyID: scl9PEwPzA-erA5tb1YqJgxxx
      keySecretRef:
        name: zerossl-eab
        key: secret
    privateKeySecretRef:
      name: zerossl
    solvers:
    - http01:
        ingress:
          class: nginx
 #}
