---
#alicloud nas

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ k8s_data_pvc.name }}
  namespace: {{ namespace }}
  labels:
    pv: {{ k8s_data_pvc.name }}
spec:
  storageClassName: datapv
  capacity:
    storage: {{ k8s_data_pvc.resources_requests }}
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: {{ k8s_data_pvc.name }}
    volumeAttributes:
      server: {{ k8s_data_pvc.server }}
      path: {{  k8s_data_pvc.path }}
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ k8s_data_pvc.name }}
  namespace: {{ namespace }}
spec:
  storageClassName: datapv
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: {{ k8s_data_pvc.resources_requests }}
  selector:
    matchLabels:
      pv: {{ k8s_data_pvc.name }}



---
#alicloud nas

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ k8s_log_pvc.name }}
  namespace: {{ namespace }}
  labels:
    pv: {{ k8s_log_pvc.name }}
spec:
  storageClassName: logpv
  capacity:
    storage: {{ k8s_log_pvc.resources_requests }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: {{ k8s_log_pvc.name }}
    volumeAttributes:
      server: {{ k8s_log_pvc.server }}
      path: {{  k8s_log_pvc.path }}
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ k8s_log_pvc.name }}
  namespace: {{ namespace }}
spec:
  storageClassName: logpv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ k8s_log_pvc.resources_requests }}
  selector:
    matchLabels:
      pv: {{ k8s_log_pvc.name }}

# #doc
# https://help.aliyun.com/document_detail/134884.html
