---
{% if k8s_version is version("1.21","<") %}
apiVersion: batch/v1beta1
{% else %}
apiVersion: batch/v1
{% endif %}
kind: CronJob
metadata:
  name: job-log-clear
  namespace: {{ namespace }}
spec:
  schedule: "1 0 * * *"
{% if k8s_version|default(1.18) is version("1.25",">") %}
  timeZone: "{{ TZ | default('Asia/Shanghai') }}"
{% endif %}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: job-log-clear
            image: egistry.aliyuncs.com/elvin/bash:find
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: log
              mountPath: "/var/log/k8s"
            - mountPath: "/etc/localtime"
              name: localtime
              readOnly: true
            command:
            - bash
            - -c
            - |
              date +"%F %T %Z %:z"
              [ "{{env}}" = "prod" ] && { d=180 ; } || { d=3 ; }
              n=$(find /var/log/k8s -type f -name *.log -mtime +$d |wc -l)
              echo "Clean Up $n logs files from $d days ago"
              find /var/log/k8s -type f -size 0c -delete
              find /var/log/k8s -type f -mtime +$d -delete
              find /var/log/k8s -type f -size +1k -name "gc.*.log"  -o -name "vm.*.log" |xargs truncate -s 0
              find /var/log/k8s -type f -mtime +0 -size +1k -name "*.log" |egrep -v "gz$" |xargs gzip
              date +"%F %T %Z %:z"

          volumes:
          - name: localtime
            hostPath:
              path: /etc/localtime
          - name: log
            persistentVolumeClaim:
              claimName: {{ k8s_log_pvc.name }}

#doc
#https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/cron-jobs/
