---

apiVersion: v1
kind: Service
metadata:
 annotations:
    #内网型号# 
    # service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-41mmnxxx
    #绑定手动创建的slb 
    service.kubernetes.io/tke-existed-lbid: lb-m5fpxxx
    #https://cloud.tencent.com/document/product/457/51812 
    # service.cloud.tencent.com/direct-access: "true"
    #LB直通Pod https://cloud.tencent.com/document/product/457/47293#step3 
 name: nginx-ingress-lb
 namespace: kube-system
spec:
 type: LoadBalancer
 externalTrafficPolicy: "Local"
 ports:
 - port: 80
   name: http
   targetPort: 80
 - port: 443
   name: https
   targetPort: 443
 selector:
   app: ingress-nginx

# #doc
# https://cloud.tencent.com/document/product/457/47293#step3
