---
- name: Check docker-compose version 
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false
  tags: never,compose

- name: Install docker-compose {{ docker_compose_version }} 
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
    force: yes
  when: >
    (docker_compose_current_version.stdout is not defined) or
    (docker_compose_current_version.stdout is defined and docker_compose_version not in docker_compose_current_version.stdout)
  tags: never,compose
