---

docker_image_name: web-demo1
docker_image_tag: "{{ web_demo1_version }}"

docker_build_service_type: nginx
docker_build_base_image: nginx:1.22-alpine
docker_build_add_conf: false
docker_build_static_list:
- name: v1
  version: "{{ web_demo1_v1_version }}"
- name: v2
  version: "{{ web_demo1_v2_version }}"

docker_build_nginx_headers:
- name: Strict-Transport-Security 
  value: "max-age=31536000; includeSubDomains; always;"
- name: Content-Security-Policy
  value: frame-ancestors 'self' *.elvin.vip https://www.baidu.com
- name: X-Frame-Options
  value: Allow-From *.elvin.vip https://www.baidu.com

k8s_pod_name: web-demo1
k8s_pod_replicas: 1
k8s_pod_resources_requests_cpu: 100m
k8s_pod_resources_requests_memory: 128Mi
k8s_pod_resources_limits_cpu: 600m
k8s_pod_resources_limits_memory: 1Gi
k8s_pod_readinessProbe_initialDelaySeconds: 10
k8s_pod_readinessProbe_periodSeconds: 5
k8s_pod_readinessProbe_failureThreshold: 3
k8s_pod_livenessProbe_initialDelaySeconds: 10

k8s_configmap_enabled: true
k8s_service_enabled: true
k8s_ingress_enabled: true
k8s_log_pvc_add: false
k8s_data_pvc_add: false
k8s_data_pvc_dir: /data
k8s_pvc_replace_permissions: false
k8s_config_profiles_active_env: false


app_domain_name: k8s-web-demo1.elvin.vip

k8s_ingress_scheme:  https
# k8s_ingress_cert_issuer: letsencrypt
k8s_ingress_cert_issuer: ''
k8s_ingress_domain_name:  app2k8s-web.elvin.vip

