---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ k8s_pod_name }}-config
  namespace: {{ namespace }}
data:
  app-domain.properties: |-

    #test config

  app-ecin.properties: |-

    #test config
